src/library/urls.py
from django.urls import path
from library.views import BandList, BandCreate, BandEdit, BandDetail, BandDelete
from library.views import AlbumList, AlbumDelete, AlbumCreate, AlbumDetail, AlbumEdit
from library.views import TrackCreate, PlaylistList, PlaylistDetail

app_name = "library"

urlpatterns = [
    path('bands', BandList.as_view(), name='bands-list'),
    path('albums', AlbumList.as_view(), name='albums-list'),
    path('create-band', BandCreate.as_view(), name='create-band'),
    path('band/<pk>', BandDetail.as_view(), name='band'),
    path('edit-band/<pk>', BandEdit.as_view(), name='edit-band'),
    path('delete-band/<pk>', BandDelete.as_view(), name='delete-band'),
    path('band/<pk>/create-album', AlbumCreate.as_view(), name='create-album'),
    path('album/<pk>', AlbumDetail.as_view(), name='album'),
    path('edit-album/<pk>', AlbumEdit.as_view(), name='edit-album'),
    path('delete-album/<pk>', AlbumDelete.as_view(), name='delete-album'),
    path('album/<pk>/create-tracks', TrackCreate.as_view(), name='create-tracks' ),
    path('playlists', PlaylistList.as_view(), name='playlists-list'),
    path('playlist/<pk>', PlaylistDetail.as_view(), name='playlist'),
]

src/musitheque/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from account.views import signup
from musitheque import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('library/', include('library.urls')),
    path('compte/', include('django.contrib.auth.urls')),
    path('compte/nouveau', signup, name="signup"),
    path('statistic/', include('statistic.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/statistic/urls.py
from django.urls import path
from statistic.views import BandByCountriesView, AlbumByYearsView, AlbumByDecadesView, AlbumByFamiliesView
from statistic.views import AlbumByGenresView, ListenedReleasedView, AlbumByRating

app_name = "statistic"

urlpatterns = [
    path('band/by_country', BandByCountriesView.as_view(), name='band-by-country'),
    path('album/by_years', AlbumByYearsView.as_view(), name='album-by-years'),
    path('album/by_decades', AlbumByDecadesView.as_view(), name='album-by-decades'),
    path('album/by_families', AlbumByFamiliesView.as_view(), name='album-by-families'),
    path('album/by_genres/<str:family>', AlbumByGenresView.as_view(), name='album-by-genres'),
    path('album/by_rating', AlbumByRating.as_view(), name='album-by-rating'),
    path('album/listened_released', ListenedReleasedView.as_view(), name='listened-released'),
]

src/library/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.utils.text import slugify


class Band(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50)
    country = models.CharField(max_length=50)
    region = models.CharField(max_length=50)
    city = models.CharField(max_length=50, blank=True)
    active = models.BooleanField(default=True)
    date_added = models.DateField(auto_now=True)
    thumbnail = models.ImageField(blank=True, upload_to='bands')

    class Meta:
        verbose_name = "Groupe"
        ordering = ["name"]

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)

        super().save(*args, **kwargs)

    # def get_absolute_url(self):
    #     return reverse('library:bands-list')


class Genre(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=50)
    family = models.CharField(max_length=50, blank=True)

    class Meta:
        verbose_name = "Genre"
        ordering = ["name"]

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)

        super().save(*args, **kwargs)


class Album(models.Model):

    ALBUM_TYPE_CHOICES = [
        ("LP", "LP"),
        ("EP", "EP"),
        ("LI", "Live")
    ]

    VOICE_STYLE_CHOICES = [
        ("HA", "Harsh"),
        ("CL", "Clean"),
        ("MX", "Mixed"),
        ("NO", "Instrumental")
    ]

    TYPE_OWNED_CHOICES = [
        ("VY", "Vynile"),
        ("NU", "Numérique"),
        ("CD", "CD"),
        ("K7", "K7")
    ]

    title = models.CharField(max_length=50, verbose_name="titre")
    slug = models.SlugField(max_length=50, blank=True)
    groupe = models.ForeignKey("Band", on_delete=models.CASCADE)
    date_released = models.DateField(blank=True, null=True, verbose_name="Date de sortie")
    date_listened = models.DateField(blank=True, null=True, verbose_name="Date d'écoute")
    date_added = models.DateField(auto_now=True, verbose_name="Date d'ajout")
    type_vocal = models.CharField(max_length=2, choices=VOICE_STYLE_CHOICES, null=True, verbose_name="Voix")
    type_album = models.CharField(max_length=2, choices=ALBUM_TYPE_CHOICES, verbose_name="Type")
    type_owned = models.CharField(max_length=2, choices=TYPE_OWNED_CHOICES, verbose_name="Type possédé", blank=True)
    genre_primary = models.ManyToManyField(Genre, related_name="primary_genre", verbose_name="Genre Primaire")
    genre_secondary = models.ManyToManyField(Genre,related_name="secondary_genre", verbose_name="Genre Secondaire", blank=True)
    number_album = models.PositiveSmallIntegerField(default=1, verbose_name="Nombre d'albums")
    owned = models.BooleanField(default=False, verbose_name="Possédé")
    rating = models.FloatField(blank=True, null=True, verbose_name="Note")
    thumbnail = models.ImageField(blank=True, upload_to='albums')

    class Meta:
        verbose_name = "Album"
        ordering = ["title"]

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)

        super().save(*args, **kwargs)


class Playlist(models.Model):

    PLAYLIST_TYPE_CHOICES = [
        ("G", "Genre"),
        ("Y", "Année"),
        ("T", "Top 10"),
        ("F", "5 Étoiles")
    ]

    name = models.CharField(max_length=50, unique=True, verbose_name="Nom")
    slug = models.SlugField(max_length=50)
    type = models.CharField(max_length=2, choices=PLAYLIST_TYPE_CHOICES)
    color = models.CharField(max_length=7, verbose_name="Couleur", blank=True)
    optional = models.BooleanField(default=False, verbose_name="Optionel")
    date_added = models.DateField(auto_now=True, blank=True, null=True, verbose_name="Ajoutée le")
    like = models.IntegerField(default=0, blank=True, null=True)
    fan = models.IntegerField(default=0, blank=True, null=True)

    class Meta:
        verbose_name = "Playlist"
        ordering = ["name"]

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)

        super().save(*args, **kwargs)


class Track(models.Model):
    title = models.CharField(max_length=50, verbose_name="Titre")
    slug = models.SlugField(max_length=50, blank=True)
    album = models.ForeignKey("Album", on_delete=models.CASCADE)
    playlist = models.ManyToManyField(Playlist, related_name="playlist", blank=True)
    number = models.IntegerField(verbose_name="Numéro")
    featuring_artist = models.CharField(max_length=50, verbose_name="featuring", blank=True, null=True)
    duration = models.DurationField(verbose_name="durée")
    favorite = models.BooleanField(blank=True, default=False, verbose_name="favori")
    date_added = models.DateField(auto_now=True)
    rating = models.FloatField(
        blank=True,
        null=True,
        validators=[MaxValueValidator(5), MinValueValidator(0)],
        verbose_name="Note",
    )

    class Meta:
        verbose_name = "Morceau"
        ordering = ["number"]

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)

        super().save(*args, **kwargs)

src/library/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView, FormView
from django.contrib.admin.widgets import AdminDateWidget
from django.views.generic.detail import SingleObjectMixin
from django.contrib.auth.mixins import UserPassesTestMixin

import api
from library.forms import TracksCreateFormSet, AlbumCreateForm
from library.models import Band, Album, Track, Playlist


class BandList(ListView):
    model = Band
    context_object_name = "bands"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        context['user'] = user
        return context


class BandCreate(UserPassesTestMixin, CreateView):
    model = Band
    template_name = "library/band_create.html"
    fields = [
        "name",
        "country",
        "region",
        "city",
        "active",
        "thumbnail",
    ]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['submit_button_value'] = "Ajouter"
        return context

    def test_func(self):
        return self.request.user.is_admin

    def get_success_url(self):
        return reverse('library:bands-list')


class BandEdit(UserPassesTestMixin, UpdateView):
    model = Band
    template_name = "library/band_create.html"
    fields = [
        "name",
        "country",
        "region",
        "city",
        "active",
        "thumbnail",
    ]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['submit_button_value'] = "Modifier"
        return context

    def get_success_url(self, **kwargs):
        band_id = self.kwargs.get('pk')
        return reverse('library:band', kwargs={'pk': band_id})

    def test_func(self):
        return self.request.user.is_admin


class BandDetail(DetailView):
    model = Band

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        band = Band.objects.get(pk=self.kwargs.get('pk'))
        album_owned, album_count = api.get_album_owned_count_for_band(band.id)
        context['albums'] = Album.objects.filter(groupe=band.id).order_by("date_released")
        context['album_owned'] = album_owned
        context['album_count'] = album_count
        return context


class BandDelete(UserPassesTestMixin, DeleteView):
    model = Band
    success_url = reverse_lazy("library:bands-list")
    context_object_name = "band"

    def test_func(self):
        return self.request.user.is_admin


class AlbumList(ListView):
    model = Album
    context_object_name = "albums"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        context['user'] = user
        return context


class AlbumCreate(UserPassesTestMixin, CreateView):
    model = Album
    template_name = "library/album_create.html"
    form_class = AlbumCreateForm

    def get_initial(self):
        groupe = get_object_or_404(Band, pk=self.kwargs.get('pk'))
        return {
            'groupe': groupe,
        }

    # Cette fonction sert à ajouter le widget DatePicker sur les champs date du formulaire
    def get_form(self, form_class=None):
        form = super(AlbumCreate, self).get_form(form_class)
        form.fields['date_released'].widget = AdminDateWidget(attrs={'type': 'date'})
        form.fields['date_listened'].widget = AdminDateWidget(attrs={'type': 'date'})
        form.fields['groupe'].disabled = True
        return form

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['submit_button_value'] = "Créer"
        return context

    def get_success_url(self):
        band_id = self.kwargs.get('pk')
        return reverse('library:band', kwargs={'pk': band_id})

    def test_func(self):
        return self.request.user.is_admin

    def form_valid(self, form):
        title = form.cleaned_data.get('title')
        groupe = form.cleaned_data.get('groupe')
        released = form.cleaned_data.get('date_released')
        listened = form.cleaned_data.get('date_listened')

        if Album.objects.filter(title=title, groupe=groupe).exists():
            form.add_error(None, "L'album existe déjà")
            return self.form_invalid(form)
        elif released > listened :
            form.add_error(None, "Vous ne pouvez pas avoir écouté un album avant sa sortie")
            return self.form_invalid(form)
        else:
            form.save()
            return redirect(self.get_success_url())

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form))


class AlbumEdit(UserPassesTestMixin, UpdateView):
    model = Album
    template_name = "library/album_create.html"
    form_class = AlbumCreateForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['submit_button_value'] = "Modifier"
        return context

    def get_success_url(self, **kwargs):
        album_id = self.kwargs.get('pk')
        return reverse('library:album', kwargs={'pk': album_id})

    def test_func(self):
        return self.request.user.is_admin


class AlbumDetail(DetailView):
    model = Album
    context_object_name = "album"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        album = Album.objects.get(pk=self.kwargs.get('pk'))
        band = Band.objects.get(name=album.groupe)
        full_duration = api.get_album_duration(album.id)
        context['tracks'] = Track.objects.filter(album=album.id).order_by("number")
        context['full_duration'] = full_duration
        context['band'] = band
        return context


class AlbumDelete(UserPassesTestMixin, DeleteView):
    model = Album
    success_url = reverse_lazy("library:albums-list")
    context_object_name = "album"

    def test_func(self):
        return self.request.user.is_admin


class TrackCreate(UserPassesTestMixin, SingleObjectMixin, FormView):
    model = Track
    template_name = "library/track_create.html"

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Album.objects.all())
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Album.objects.all())
        return super().post(request, *args, **kwargs)

    def get_form(self, form_class=None):
        return TracksCreateFormSet(**self.get_form_kwargs(), instance=self.object)

    def form_valid(self, form):
        form.save()

        messages.add_message(
            self.request,
            messages.SUCCESS,
            "Les changements ont été sauvegardés."
        )

        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self, **kwargs):
        album_id = self.kwargs.get('pk')
        return reverse('library:album', kwargs={'pk': album_id})

    def test_func(self):
        return self.request.user.is_admin


class PlaylistList(ListView):
    model = Playlist
    context_object_name = "playlists"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        context['user'] = user
        return context


class PlaylistDetail(DetailView):
    model = Playlist
    context_object_name = "playlist"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        playlist = Playlist.objects.get(pk=self.kwargs.get('pk'))
        number_of_tracks = Track.objects.filter(playlist__id=playlist.pk).count()
        full_duration = api.get_playlist_duration(playlist.pk)
        context['tracks'] = Track.objects.filter(playlist__id=playlist.pk).order_by("title")
        context['full_duration'] = full_duration
        context['number_of_tracks'] = number_of_tracks
        return context

src/library/templates/library/album_confirm_delete.html
{% extends 'base_library.html' %}

{% block title %}
    <title>Supprimer un album</title>
{% endblock %}

{% block content %}

    <div class="formContainer">
        <h1>Supprimer l'album {{album.tile}}</h1>
        <form method="POST" enctype="multipart/form-data" class="form form-delete">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Oui, Supprimer" class="btn btn-delete">
        </form>
    </div>



{% endblock %}

src/library/templates/library/album_detail.html
{% extends 'base_library.html' %}
{%load static%}
{% load library_extras %}

{% block title%} <title>{{ album.title }}</title> {% endblock %}

{% block content %}
    <div id="library-content">
        <div class="library-img">
                <img src="{{ album.thumbnail.url}}" alt="{{album.slug}}">
                <form action="{% url 'library:edit-album' pk=album.pk %}">
                    <button class="btn btn-edit">Modifier l'album</button>
                </form>
                <form action="{% url 'library:delete-album' pk=album.pk %}">
                    <button class="btn btn-delete">Supprimer l'album</button>
                </form>
                <form action="{% url 'library:create-tracks' pk=album.pk %}">
                    <button class="btn btn-edit">Modifier les morceaux</button>
                </form>
        </div>
        <div class="bio">
            <h1>{{ album.title }}</h1>
            <div class="bio-info">
                <p>Groupe : <a href="{% url 'library:band' pk=band.pk %}">{{ album.groupe.name }}</a></p>
                <p>Sorti le {{ album.date_released }}</p>
                <p>Écouté en {{ album.date_listened|date:'F Y' }}</p>
                <p>Voix - {{ album.get_type_vocal_display }}</p>
                <p>Genre Primaire - {% for genre_primary in album.genre_primary.all %}{{ genre_primary }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
                <p>Genre Secondaire -
                    {% if album.genre_secondary.all %}
                        {% for genre_secondary in album.genre_secondary.all %}
                            {{ genre_secondary }}{% if not forloop.last %}, {% endif %}
                        {% endfor %}
                    {% else %}
                        Aucun
                    {% endif %}
                </p>
                <p>
                    {% if album.rating %}
                        {{ album.rating }}/5
                    {% else %}
                        Non Noté
                    {% endif %}
                </p>
            </div>
        </div>
        <div class="tableContainer">
            <h1>Liste des morceaux</h1>
            <table>
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Titre</th>
                        <th>Durée</th>
                        <th>Playlist</th>
                        <th>Note</th>
                    </tr>
                </thead>
                <tbody>

                        {% for track in tracks %}
                        <tr>
                            <td class="track-number">{{ track.number }}</td>
                            <td class="track-title">{{track.title}}</td>
                            <td class="track-duration">{{track.duration}}</td>
                            <td class="track-playlist">
                                {% for playlist in track.playlist.all %}
                                    {% if playlist.type == "G" %}
                                    <span class="fa fa-music" title="{{ playlist.name }}" style="color: {{playlist.color}};"></span>
                                    {% elif playlist.type == "Y"%}
                                    <span class="fa fa-calendar-check-o" title="{{ playlist.name }}"></span>
                                    {% elif playlist.type == "T"%}
                                    <span class="fa fa-arrow-circle-up" title="{{ playlist.name }}"></span>
                                    {% else %}
                                    <span class="fa fa-heart" title="{{ playlist.name }}"></span>
                                    {% endif %}
                                {% endfor %}
                            </td>
                            <td class="track-rating">
                                {% if track.rating %}
                                    {% for i in track.rating|time %}
                                        <span class="fa fa-star checked"></span>
                                    {% endfor %}
                                    {% if track.rating|last == "5" %}
                                        <span class="fa fa-star-half-full"></span>
                                    {% endif %}
                                    {% for j in  track.rating|minus|time %}
                                        <span class="fa fa-star-o"></span>
                                    {% endfor %}
                                    {{track.rating}}
                                {% endif %}
                            </td>
                        </tr>
                        {% endfor %}
                        <tr class="lastTR">
                            <td></td>
                            <td></td>
                            <td>{{full_duration}}</td>
                            <td></td>
                            <td></td>
                        </tr>
                </tbody>
            </table>
        </div>
    </div>


{% endblock %}

src/library/templates/library/album_list.html
{% extends 'base_library.html' %}

{% block title %}
    <title>Accueil de la musithèque</title>
{% endblock %}

{% block nav %}<input type="text" id="recherche" placeholder="Rechercher" onkeyup="search()">{% endblock %}


{% block content %}

<div class="bandList">
    <ul id="listeGroupe">
        <li id="albumCount">
            <div class="img-band">
                <p>{{ albums.count }} albums</p>
            </div>
            <div class="name name-centered">
                <a href="{% url 'statistic:album-by-years' %}">Stats des albums</a>
            </div>
        </li>

        {% for album in albums %}
            <li id="{{ album.slug }}">
                <div class="img-band">
                    <img src="{{ album.thumbnail.url}}" alt="{{album.slug}}">
                </div>
                <div class="name name-centered">
                    <a href="{% url 'library:album' pk=album.pk %}">{{ album.title }}</a>
                </div>
            </li>
        {% endfor %}
    </ul>
</div>
<script>
    var list = document.querySelector("#listeGroupe");
    var items = list.children;
    var loading = false;
    var index = 20;

    for (var i = 20; i < items.length; i++) {
      items[i].style.display = "none";
    }

    window.addEventListener("scroll", function() {
      if (loading) return;
      if (document.body.clientHeight - window.innerHeight - window.scrollY < 20) {
        loading = true;
        for (var i = index; i < index + 20; i++) {
          if (i < items.length) {
            items[i].style.display = "block";
          } else {
            break;
          }
        }
        index += 20;
        loading = false;
      }
    });
</script>
{% endblock %}

src/library/templates/library/band_confirm_delete.html
{% extends 'base_library.html' %}

{% block title %}
    <title>Supprimer un groupe</title>
{% endblock %}

{% block content %}

    <div class="formContainer">
        <form method="POST" class="form form-delete">
        {% csrf_token %}
        <p>Êtes-vous sûr de vouloir supprimer "{{ band.name }}"</p>
        <input type="submit" value="Oui, supprimer" class="btn btn-delete">
    </form>
    </div>

{% endblock %}

src/library/templates/library/band_detail.html
{% extends 'base_library.html' %}
{%load static%}

{% block title%} <title>{{ band.name }}</title> {% endblock %}

{% block content %}
    <div id="library-content">
        <div class="library-img">
            <img src="{{ band.thumbnail.url}}" alt="{{band.slug}}">
            <form action="{% url 'library:edit-band' pk=band.pk %}">
                <button class="btn btn-edit">Modifier l'artiste</button>
            </form>
            <form action="{% url 'library:delete-band' pk=band.pk %}">
                <button class="btn btn-delete">Supprimer l'artiste</button>
            </form>
            <form action="{% url 'library:create-album' pk=band.pk %}">
                <button class="btn btn-submit">Ajouter un Album</button>
            </form>
        </div>
        <div class="bio">
            <h1>{{ band.name }}</h1>
            <div class="bio-info">
                <p>Pays - {{ band.country }}</p>
                <p>Région - {{ band.region }}</p>
                <p>Ville - {{ band.city }}</p>
                <p>Ajouté le : {{ band.date_added }}</p>
                <p>
                    {% if band.active %}
                        Actif
                    {% else %}
                        Inactif
                    {% endif %}
                </p>
                <p>Nombre d'album(s) possédé(s): {{ album_owned }}/{{ album_count }}</p>
            </div>
        </div>
        <div class="tableContainer">
            <h1>Albums</h1>
            <table>
                <tbody>
                    {% for album in albums %}
                        {% if album.type_album == "LP" %}
                            <tr>
                                <td><img src="{{ album.thumbnail.url }}" alt="{{album.slug}}" width="75" height="75"></td>
                                <td><a href="{% url 'library:album' pk=album.pk %}">{{ album.title }}</a></td>
                                <td>{{album.date_released|date:'Y'}}</td>
                                <td>
                                    {% if album.rating %}
                                        {{ album.rating }}/5
                                    {% else %}
                                        Non Noté
                                    {% endif %}
                                </td>
                            </tr>
                        {% endif %}
                    {% endfor %}
                </tbody>
            </table>
            <h1>EPs</h1>
            <table>
                <tbody>
                    {% for album in albums %}
                        {% if album.type_album == "EP" %}
                            <tr>
                                <td><img src="{{ album.thumbnail.url }}" alt="{{album.slug}}" width="75" height="75"></td>
                                <td><a href="{% url 'library:album' pk=album.pk %}">{{ album.title }}</a></td>
                                <td>{{album.date_released|date:'Y'}}</td>
                                <td>
                                    {% if album.rating %}
                                        {{ album.rating }}/5
                                    {% else %}
                                        Non Noté
                                    {% endif %}
                                </td>
                            </tr>
                        {% endif %}
                    {% endfor %}
                </tbody>
            </table>
            <h1>Lives</h1>
            <table>
                <tbody>
                    {% for album in albums %}
                        {% if album.type_album == "LI" %}
                            <tr>
                                <td><img src="{{ album.thumbnail.url }}" alt="{{album.slug}}" width="75" height="75"></td>
                                <td><a href="{% url 'library:album' pk=album.pk %}">{{ album.title }}</a></td>
                                <td>{{album.date_released|date:'Y'}}</td>
                                <td>
                                    {% if album.rating %}
                                        {{ album.rating }}/5
                                    {% else %}
                                        Non Noté
                                    {% endif %}
                                </td>
                            </tr>
                        {% endif %}
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

src/library/templates/library/band_list.html
{% extends 'base_library.html' %}


{% block title %}
    <title>Accueil de la musithèque</title>
{% endblock %}

{% block nav %}<input type="text" id="recherche" placeholder="Rechercher" onkeyup="search()">{% endblock %}


{% block content %}

<div class="bandList">
    <ul id="listeGroupe">
        <li id="addBandButton">
            <div class="img-band">
                <p>{{ bands.count }} artistes</p>
            </div>
            <div class="name name-centered">
                <a href="{% url 'library:create-band' %}">Ajouter un artiste</a>
            </div>
        </li>
        {% for band in bands %}
            <li id="{{ band.slug }}">
                <div class="img-band">
                    <img src="{{ band.thumbnail.url}}" alt="{{band.slug}}">
                </div>
                <div class="name name-centered">
                    <a href="{% url 'library:band' pk=band.pk %}">{{ band.name }}</a>
                </div>
            </li>
        {% endfor %}
    </ul>
</div>
<script>
    var list = document.querySelector("#listeGroupe");
    var items = list.children;
    var loading = false;
    var index = 20;

    for (var i = 20; i < items.length; i++) {
      items[i].style.display = "none";
    }

    window.addEventListener("scroll", function() {
      if (loading) return;
      if (document.body.clientHeight - window.innerHeight - window.scrollY < 20) {
        loading = true;
        for (var i = index; i < index + 20; i++) {
          if (i < items.length) {
            items[i].style.display = "block";
          } else {
            break;
          }
        }
        index += 20;
        loading = false;
      }
    });
</script>

{% endblock %}

src/library/templates/library/playlist_list.html
{% extends 'base_library.html' %}


{% block title %}
    <title>Accueil de la musithèque</title>
{% endblock %}

{% block nav %}<input type="text" id="recherche" placeholder="Rechercher" onkeyup="search()">{% endblock %}


{% block content %}

    <div class="bandList">
        <ul id="listeGroupe">
            <li id="addPlaylistButton">
                <div class="img-band">
                    <img src="https://picsum.photos/250/250" alt="Random Image">
                </div>
                <div class="name name-centered">
                    <a href="{% url 'library:create-band' %}">Ajouter une playlist</a>
                </div>
            </li>

            {% for playlist in playlists %}
                <li id="{{ playlist.slug }}">
                    <div class="img-band">
                        <img src="https://picsum.photos/250/250" alt="Random Image">
                    </div>
                    <div class="name name-centered">
                        <a href="{% url 'library:playlist' pk=playlist.pk %}">{{ playlist.name }}</a>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>

{% endblock %}

src/library/templates/library/search.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>