src/library/urls.py
from django.urls import path
from library.views import BandList, BandCreate, BandEdit, BandDetail, BandDelete
from library.views import AlbumList, AlbumDelete, AlbumCreate, AlbumDetail, AlbumEdit
from library.views import TrackCreate, PlaylistList, PlaylistDetail

app_name = "library"

urlpatterns = [
    path('bands', BandList.as_view(), name='bands-list'),
    path('albums', AlbumList.as_view(), name='albums-list'),
    path('create-band', BandCreate.as_view(), name='create-band'),
    path('band/<pk>', BandDetail.as_view(), name='band'),
    path('edit-band/<pk>', BandEdit.as_view(), name='edit-band'),
    path('delete-band/<pk>', BandDelete.as_view(), name='delete-band'),
    path('band/<pk>/create-album', AlbumCreate.as_view(), name='create-album'),
    path('album/<pk>', AlbumDetail.as_view(), name='album'),
    path('edit-album/<pk>', AlbumEdit.as_view(), name='edit-album'),
    path('delete-album/<pk>', AlbumDelete.as_view(), name='delete-album'),
    path('album/<pk>/create-tracks', TrackCreate.as_view(), name='create-tracks' ),
    path('playlists', PlaylistList.as_view(), name='playlists-list'),
    path('playlist/<pk>', PlaylistDetail.as_view(), name='playlist'),
]

src/musitheque/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from account.views import signup
from musitheque import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('library/', include('library.urls')),
    path('compte/', include('django.contrib.auth.urls')),
    path('compte/nouveau', signup, name="signup"),
    path('statistic/', include('statistic.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/statistic/urls.py
from django.urls import path
from statistic.views import BandByCountriesView, AlbumByYearsView, AlbumByDecadesView, AlbumByFamiliesView
from statistic.views import AlbumByGenresView, ListenedReleasedView, AlbumByRating

app_name = "statistic"

urlpatterns = [
    path('band/by_country', BandByCountriesView.as_view(), name='band-by-country'),
    path('album/by_years', AlbumByYearsView.as_view(), name='album-by-years'),
    path('album/by_decades', AlbumByDecadesView.as_view(), name='album-by-decades'),
    path('album/by_families', AlbumByFamiliesView.as_view(), name='album-by-families'),
    path('album/by_genres/<str:family>', AlbumByGenresView.as_view(), name='album-by-genres'),
    path('album/by_rating', AlbumByRating.as_view(), name='album-by-rating'),
    path('album/listened_released', ListenedReleasedView.as_view(), name='listened-released'),
]

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    {% block title %}
    {% endblock %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="{% static 'javascript/script.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.9.1/dist/chart.min.js"></script>
</head>
<body>

    <nav>
        <div class="navbar">
            <a href="{% url 'library:bands-list' %}">Artistes</a>
            <a href="{% url 'library:albums-list' %}">Albums</a>
            <a href="{% url 'statistic:stats-band' %}">Statistiques des groupes</a>
            <a href="{% url 'statistic:stats-album' %}">Statistiques des albums</a>
            {% block nav %}{% endblock %}
        </div>
    </nav>


    <section id="library">
        {% block content %}

        {% endblock %}
    </section>
</body>
</html>

src/templates/base_library.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    {% block title %}
    {% endblock %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}">
    <script src="{% static 'javascript/script.js'%}"></script>
    <script src="{% static 'javascript/multiselect-dropdown.js'%}" ></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.9.1/dist/chart.min.js"></script>
    {% block script %}
    {% endblock %}
</head>
<body>

    <nav class="nav">
        <div class="navbar">
            <a href="{% url 'library:bands-list' %}">Artistes</a>
            <a href="{% url 'library:albums-list' %}">Albums</a>
            <a href="{% url 'library:playlists-list' %}">Playlists</a>
            <a href="{% url 'statistic:band-by-country' %}">Statistiques</a>
            {% block nav %}{% endblock %}
        </div>
    </nav>


    <section id="library">
        {% block content %}
        {% endblock %}
    </section>
</body>
</html>

src/templates/base_statistic.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    {% block title %}
    {% endblock %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}">
    <script src="{% static 'javascript/script.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.9.1/dist/chart.min.js"></script>
    {% block script %}
    {% endblock %}
</head>
<body>

    <nav>
        <div class="navbar">
            <a href="{% url 'library:bands-list' %}">Artistes</a>
            <a href="{% url 'library:albums-list' %}">Albums</a>
            <a href="{% url 'library:playlists-list' %}">Playlists</a>
            <a href="{% url 'statistic:band-by-country' %}">Statistiques</a>
            {% block nav %}{% endblock %}
        </div>
    </nav>

    <section id="statistic">
        <div id="statistic-content">
        <nav class="collapse">
            <ul>
                <li>Artistes
                    <ul>
                        <li><a href="{% url 'statistic:band-by-country' %}">Par pays</a></li>
                    </ul>
                </li>
                <li>Albums
                    <ul>
                        <li><a href="{% url 'statistic:album-by-years' %}">Par années</a></li>
                        <li><a href="{% url 'statistic:album-by-rating' %}">Par notes</a></li>
                        <li><a href="{% url 'statistic:album-by-decades' %}">Par décénies</a></li>
                        <li><a href="{% url 'statistic:album-by-families' %}">Par famille</a></li>
                        <li>Par genre
                            <ul>
                                <li><a href="{% url 'statistic:album-by-genres' family='Ambient'%}">D'Ambient'</a></li>
                                <li><a href="{% url 'statistic:album-by-genres' family='Country'%}">De Country</a></li>
                                <li><a href="{% url 'statistic:album-by-genres' family='Dance'%}">De Dance</a></li>
                                <li><a href="{% url 'statistic:album-by-genres' family='Electronic'%}">D'Electro</a></li>
                                <li><a href="{% url 'statistic:album-by-genres' family='Folk'%}">De Folk</a></li>
                                <li><a href="{% url 'statistic:album-by-genres' family='Hip Hop'%}">De Hip Hop</a></li>
                                <li><a href="{% url 'statistic:album-by-genres' family='Jazz'%}">De Jazz</a></li>
                                <li><a href="{% url 'statistic:album-by-genres' family='Metal'%}">De Métal</a></li>
                                <li><a href="{% url 'statistic:album-by-genres' family='Regional'%}">De Musique Régionale</a></li>
                                <li><a href="{% url 'statistic:album-by-genres' family='Pop'%}">De Pop</a></li>
                                <li><a href="{% url 'statistic:album-by-genres' family='Punk'%}">De Punk</a></li>
                                <li><a href="{% url 'statistic:album-by-genres' family='Psychedelia'%}">De Psychedelia</a></li>
                                <li><a href="{% url 'statistic:album-by-genres' family='R&B'%}">De R&B</a></li>
                                <li><a href="{% url 'statistic:album-by-genres' family='Rock'%}">De Rock</a></li>
                            </ul>
                        </li>
                        <li><a href="{% url 'statistic:listened-released' %}">Par écoute</a></li>
                    </ul>
                </li>
            </ul>
        </nav>
        {% block content %}
        {% endblock %}
        </div>
    </section>


</body>
</html>